/********************************************************************************
** Form generated from reading UI file 'configprocess.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CONFIGPROCESS_H
#define UI_CONFIGPROCESS_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ConfigProcess
{
public:
    QDialogButtonBox *buttonBox;
    QTabWidget *tabWidget;
    QWidget *tab_Original;
    QLabel *label_Original;
    QWidget *tab_Fundo;
    QLabel *label_Fundo;
    QWidget *tab_Subt;
    QLabel *label_Subt;
    QWidget *tab_Proc;
    QLabel *label_Proc;
    QWidget *tab;
    QLabel *label_Limiar1;
    QWidget *tab_2;
    QLabel *label_Limiar2;
    QWidget *tab_3;
    QLabel *label_Soma;
    QWidget *tab_4;
    QLabel *label_Open;
    QWidget *tab_5;
    QLabel *label_Close;
    QTabWidget *tabWidget_2;
    QWidget *tab_Original_2;
    QLabel *label_Original_2;
    QWidget *tab_Fundo_2;
    QLabel *label_Fundo_2;
    QWidget *tab_Subt_2;
    QLabel *label_Subt_2;
    QWidget *tab_Proc_2;
    QLabel *label_Proc_2;
    QWidget *tab_6;
    QLabel *label_Limiar1_2;
    QWidget *tab_7;
    QLabel *label_Limiar2_2;
    QWidget *tab_8;
    QLabel *label_Soma_2;
    QWidget *tab_9;
    QLabel *label_Open_2;
    QWidget *tab_10;
    QLabel *label_Close_2;
    QGroupBox *groupBox_2;
    QSlider *Slider_Rmin;
    QSlider *Slider_Gmin;
    QSlider *Slider_Bmin;
    QSlider *Slider_Rmax;
    QSlider *Slider_Gmax;
    QSlider *Slider_Bmax;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_Rmin;
    QLabel *label_Gmin;
    QLabel *label_Bmin;
    QLabel *label_Rmax;
    QLabel *label_Gmax;
    QLabel *label_Bmax;
    QGroupBox *groupBox_5;
    QGroupBox *groupBox;
    QRadioButton *filter3;
    QRadioButton *filter5;
    QRadioButton *filter7;
    QRadioButton *filter9;
    QRadioButton *filter11;
    QRadioButton *filter13;
    QRadioButton *filter15;
    QRadioButton *filter17;
    QRadioButton *filter1;
    QRadioButton *filter19;
    QRadioButton *filter21;
    QRadioButton *filter23;
    QGroupBox *groupBox_8;
    QGroupBox *groupBox_4;
    QRadioButton *close2;
    QRadioButton *close3;
    QRadioButton *close4;
    QRadioButton *close5;
    QRadioButton *close6;
    QRadioButton *close7;
    QRadioButton *close8;
    QRadioButton *close9;
    QRadioButton *close1;
    QRadioButton *close10;
    QRadioButton *close11;
    QRadioButton *close12;
    QGroupBox *groupBox_3;
    QRadioButton *open2;
    QRadioButton *open3;
    QRadioButton *open4;
    QRadioButton *open5;
    QRadioButton *open6;
    QRadioButton *open7;
    QRadioButton *open8;
    QRadioButton *open9;
    QRadioButton *open1;
    QRadioButton *open10;
    QRadioButton *open11;
    QRadioButton *open12;
    QGroupBox *groupBox_6;
    QRadioButton *bot_cam1;
    QRadioButton *bot_cam2;
    QGroupBox *groupBox_7;
    QSlider *Slider_Rmin_2;
    QSlider *Slider_Gmin_2;
    QSlider *Slider_Bmin_2;
    QSlider *Slider_Rmax_2;
    QSlider *Slider_Gmax_2;
    QSlider *Slider_Bmax_2;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_Rmin2;
    QLabel *label_Gmin2;
    QLabel *label_Bmin2;
    QLabel *label_Rmax2;
    QLabel *label_Gmax2;
    QLabel *label_Bmax2;
    QPushButton *bot_Default;

    void setupUi(QDialog *ConfigProcess)
    {
        if (ConfigProcess->objectName().isEmpty())
            ConfigProcess->setObjectName(QStringLiteral("ConfigProcess"));
        ConfigProcess->resize(1366, 768);
        QIcon icon;
        icon.addFile(QStringLiteral(":/images/images/Objectif-photo-Logo-1.png"), QSize(), QIcon::Normal, QIcon::On);
        ConfigProcess->setWindowIcon(icon);
        buttonBox = new QDialogButtonBox(ConfigProcess);
        buttonBox->setObjectName(QStringLiteral("buttonBox"));
        buttonBox->setGeometry(QRect(0, 630, 171, 32));
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        tabWidget = new QTabWidget(ConfigProcess);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(190, 10, 580, 461));
        tab_Original = new QWidget();
        tab_Original->setObjectName(QStringLiteral("tab_Original"));
        label_Original = new QLabel(tab_Original);
        label_Original->setObjectName(QStringLiteral("label_Original"));
        label_Original->setGeometry(QRect(10, 10, 550, 412));
        label_Original->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget->addTab(tab_Original, QString());
        tab_Fundo = new QWidget();
        tab_Fundo->setObjectName(QStringLiteral("tab_Fundo"));
        label_Fundo = new QLabel(tab_Fundo);
        label_Fundo->setObjectName(QStringLiteral("label_Fundo"));
        label_Fundo->setGeometry(QRect(10, 10, 550, 412));
        label_Fundo->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget->addTab(tab_Fundo, QString());
        tab_Subt = new QWidget();
        tab_Subt->setObjectName(QStringLiteral("tab_Subt"));
        label_Subt = new QLabel(tab_Subt);
        label_Subt->setObjectName(QStringLiteral("label_Subt"));
        label_Subt->setGeometry(QRect(10, 10, 550, 412));
        label_Subt->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget->addTab(tab_Subt, QString());
        tab_Proc = new QWidget();
        tab_Proc->setObjectName(QStringLiteral("tab_Proc"));
        label_Proc = new QLabel(tab_Proc);
        label_Proc->setObjectName(QStringLiteral("label_Proc"));
        label_Proc->setGeometry(QRect(10, 10, 550, 412));
        label_Proc->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget->addTab(tab_Proc, QString());
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        label_Limiar1 = new QLabel(tab);
        label_Limiar1->setObjectName(QStringLiteral("label_Limiar1"));
        label_Limiar1->setGeometry(QRect(10, 10, 550, 412));
        label_Limiar1->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        label_Limiar2 = new QLabel(tab_2);
        label_Limiar2->setObjectName(QStringLiteral("label_Limiar2"));
        label_Limiar2->setGeometry(QRect(10, 10, 550, 412));
        label_Limiar2->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        label_Soma = new QLabel(tab_3);
        label_Soma->setObjectName(QStringLiteral("label_Soma"));
        label_Soma->setGeometry(QRect(10, 10, 550, 412));
        label_Soma->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        label_Open = new QLabel(tab_4);
        label_Open->setObjectName(QStringLiteral("label_Open"));
        label_Open->setGeometry(QRect(10, 10, 550, 412));
        label_Open->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        label_Close = new QLabel(tab_5);
        label_Close->setObjectName(QStringLiteral("label_Close"));
        label_Close->setGeometry(QRect(10, 10, 550, 412));
        label_Close->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget->addTab(tab_5, QString());
        tabWidget_2 = new QTabWidget(ConfigProcess);
        tabWidget_2->setObjectName(QStringLiteral("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(770, 10, 580, 461));
        tab_Original_2 = new QWidget();
        tab_Original_2->setObjectName(QStringLiteral("tab_Original_2"));
        label_Original_2 = new QLabel(tab_Original_2);
        label_Original_2->setObjectName(QStringLiteral("label_Original_2"));
        label_Original_2->setGeometry(QRect(10, 10, 550, 412));
        label_Original_2->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget_2->addTab(tab_Original_2, QString());
        tab_Fundo_2 = new QWidget();
        tab_Fundo_2->setObjectName(QStringLiteral("tab_Fundo_2"));
        label_Fundo_2 = new QLabel(tab_Fundo_2);
        label_Fundo_2->setObjectName(QStringLiteral("label_Fundo_2"));
        label_Fundo_2->setGeometry(QRect(10, 10, 550, 412));
        label_Fundo_2->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget_2->addTab(tab_Fundo_2, QString());
        tab_Subt_2 = new QWidget();
        tab_Subt_2->setObjectName(QStringLiteral("tab_Subt_2"));
        label_Subt_2 = new QLabel(tab_Subt_2);
        label_Subt_2->setObjectName(QStringLiteral("label_Subt_2"));
        label_Subt_2->setGeometry(QRect(10, 10, 550, 412));
        label_Subt_2->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget_2->addTab(tab_Subt_2, QString());
        tab_Proc_2 = new QWidget();
        tab_Proc_2->setObjectName(QStringLiteral("tab_Proc_2"));
        label_Proc_2 = new QLabel(tab_Proc_2);
        label_Proc_2->setObjectName(QStringLiteral("label_Proc_2"));
        label_Proc_2->setGeometry(QRect(10, 10, 550, 412));
        label_Proc_2->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget_2->addTab(tab_Proc_2, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        label_Limiar1_2 = new QLabel(tab_6);
        label_Limiar1_2->setObjectName(QStringLiteral("label_Limiar1_2"));
        label_Limiar1_2->setGeometry(QRect(10, 10, 550, 412));
        label_Limiar1_2->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget_2->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        label_Limiar2_2 = new QLabel(tab_7);
        label_Limiar2_2->setObjectName(QStringLiteral("label_Limiar2_2"));
        label_Limiar2_2->setGeometry(QRect(10, 10, 550, 412));
        label_Limiar2_2->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget_2->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QStringLiteral("tab_8"));
        label_Soma_2 = new QLabel(tab_8);
        label_Soma_2->setObjectName(QStringLiteral("label_Soma_2"));
        label_Soma_2->setGeometry(QRect(10, 10, 550, 412));
        label_Soma_2->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget_2->addTab(tab_8, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QStringLiteral("tab_9"));
        label_Open_2 = new QLabel(tab_9);
        label_Open_2->setObjectName(QStringLiteral("label_Open_2"));
        label_Open_2->setGeometry(QRect(10, 10, 550, 412));
        label_Open_2->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget_2->addTab(tab_9, QString());
        tab_10 = new QWidget();
        tab_10->setObjectName(QStringLiteral("tab_10"));
        label_Close_2 = new QLabel(tab_10);
        label_Close_2->setObjectName(QStringLiteral("label_Close_2"));
        label_Close_2->setGeometry(QRect(10, 10, 550, 412));
        label_Close_2->setStyleSheet(QStringLiteral("background-color: rgb(200, 200, 200);"));
        tabWidget_2->addTab(tab_10, QString());
        groupBox_2 = new QGroupBox(ConfigProcess);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(190, 470, 571, 211));
        Slider_Rmin = new QSlider(groupBox_2);
        Slider_Rmin->setObjectName(QStringLiteral("Slider_Rmin"));
        Slider_Rmin->setGeometry(QRect(60, 20, 400, 22));
        Slider_Rmin->setMaximum(255);
        Slider_Rmin->setOrientation(Qt::Horizontal);
        Slider_Gmin = new QSlider(groupBox_2);
        Slider_Gmin->setObjectName(QStringLiteral("Slider_Gmin"));
        Slider_Gmin->setGeometry(QRect(60, 50, 400, 22));
        Slider_Gmin->setMaximum(255);
        Slider_Gmin->setOrientation(Qt::Horizontal);
        Slider_Bmin = new QSlider(groupBox_2);
        Slider_Bmin->setObjectName(QStringLiteral("Slider_Bmin"));
        Slider_Bmin->setGeometry(QRect(60, 80, 400, 22));
        Slider_Bmin->setMaximum(255);
        Slider_Bmin->setOrientation(Qt::Horizontal);
        Slider_Rmax = new QSlider(groupBox_2);
        Slider_Rmax->setObjectName(QStringLiteral("Slider_Rmax"));
        Slider_Rmax->setGeometry(QRect(60, 110, 400, 22));
        Slider_Rmax->setMaximum(255);
        Slider_Rmax->setOrientation(Qt::Horizontal);
        Slider_Gmax = new QSlider(groupBox_2);
        Slider_Gmax->setObjectName(QStringLiteral("Slider_Gmax"));
        Slider_Gmax->setGeometry(QRect(60, 140, 400, 22));
        Slider_Gmax->setMaximum(255);
        Slider_Gmax->setOrientation(Qt::Horizontal);
        Slider_Bmax = new QSlider(groupBox_2);
        Slider_Bmax->setObjectName(QStringLiteral("Slider_Bmax"));
        Slider_Bmax->setGeometry(QRect(60, 170, 400, 22));
        Slider_Bmax->setMaximum(255);
        Slider_Bmax->setOrientation(Qt::Horizontal);
        label_19 = new QLabel(groupBox_2);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(20, 20, 47, 13));
        label_20 = new QLabel(groupBox_2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(20, 50, 47, 13));
        label_21 = new QLabel(groupBox_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(20, 80, 47, 13));
        label_22 = new QLabel(groupBox_2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(20, 110, 47, 13));
        label_23 = new QLabel(groupBox_2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(20, 140, 47, 13));
        label_24 = new QLabel(groupBox_2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(20, 170, 47, 13));
        label_Rmin = new QLabel(groupBox_2);
        label_Rmin->setObjectName(QStringLiteral("label_Rmin"));
        label_Rmin->setGeometry(QRect(490, 20, 47, 13));
        label_Rmin->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_Rmin->setAlignment(Qt::AlignCenter);
        label_Gmin = new QLabel(groupBox_2);
        label_Gmin->setObjectName(QStringLiteral("label_Gmin"));
        label_Gmin->setGeometry(QRect(490, 50, 47, 13));
        label_Gmin->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_Gmin->setAlignment(Qt::AlignCenter);
        label_Bmin = new QLabel(groupBox_2);
        label_Bmin->setObjectName(QStringLiteral("label_Bmin"));
        label_Bmin->setGeometry(QRect(490, 80, 47, 13));
        label_Bmin->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_Bmin->setAlignment(Qt::AlignCenter);
        label_Rmax = new QLabel(groupBox_2);
        label_Rmax->setObjectName(QStringLiteral("label_Rmax"));
        label_Rmax->setGeometry(QRect(490, 110, 47, 13));
        label_Rmax->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_Rmax->setAlignment(Qt::AlignCenter);
        label_Gmax = new QLabel(groupBox_2);
        label_Gmax->setObjectName(QStringLiteral("label_Gmax"));
        label_Gmax->setGeometry(QRect(490, 140, 47, 13));
        label_Gmax->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_Gmax->setAlignment(Qt::AlignCenter);
        label_Bmax = new QLabel(groupBox_2);
        label_Bmax->setObjectName(QStringLiteral("label_Bmax"));
        label_Bmax->setGeometry(QRect(490, 170, 47, 13));
        label_Bmax->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_Bmax->setAlignment(Qt::AlignCenter);
        groupBox_5 = new QGroupBox(ConfigProcess);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(0, 110, 191, 361));
        groupBox = new QGroupBox(groupBox_5);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 20, 171, 101));
        filter3 = new QRadioButton(groupBox);
        filter3->setObjectName(QStringLiteral("filter3"));
        filter3->setGeometry(QRect(50, 30, 82, 17));
        filter5 = new QRadioButton(groupBox);
        filter5->setObjectName(QStringLiteral("filter5"));
        filter5->setGeometry(QRect(90, 30, 82, 17));
        filter7 = new QRadioButton(groupBox);
        filter7->setObjectName(QStringLiteral("filter7"));
        filter7->setGeometry(QRect(130, 30, 82, 17));
        filter7->setCheckable(true);
        filter7->setChecked(false);
        filter9 = new QRadioButton(groupBox);
        filter9->setObjectName(QStringLiteral("filter9"));
        filter9->setGeometry(QRect(10, 50, 82, 17));
        filter11 = new QRadioButton(groupBox);
        filter11->setObjectName(QStringLiteral("filter11"));
        filter11->setGeometry(QRect(50, 50, 82, 17));
        filter13 = new QRadioButton(groupBox);
        filter13->setObjectName(QStringLiteral("filter13"));
        filter13->setGeometry(QRect(90, 50, 82, 17));
        filter15 = new QRadioButton(groupBox);
        filter15->setObjectName(QStringLiteral("filter15"));
        filter15->setGeometry(QRect(130, 50, 82, 17));
        filter17 = new QRadioButton(groupBox);
        filter17->setObjectName(QStringLiteral("filter17"));
        filter17->setGeometry(QRect(10, 70, 82, 17));
        filter1 = new QRadioButton(groupBox);
        filter1->setObjectName(QStringLiteral("filter1"));
        filter1->setGeometry(QRect(10, 30, 31, 17));
        filter19 = new QRadioButton(groupBox);
        filter19->setObjectName(QStringLiteral("filter19"));
        filter19->setGeometry(QRect(50, 70, 82, 17));
        filter21 = new QRadioButton(groupBox);
        filter21->setObjectName(QStringLiteral("filter21"));
        filter21->setGeometry(QRect(90, 70, 82, 17));
        filter23 = new QRadioButton(groupBox);
        filter23->setObjectName(QStringLiteral("filter23"));
        filter23->setGeometry(QRect(130, 70, 82, 17));
        groupBox_8 = new QGroupBox(groupBox_5);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(0, 130, 191, 361));
        groupBox_4 = new QGroupBox(groupBox_8);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 130, 171, 101));
        groupBox_4->setFlat(false);
        groupBox_4->setCheckable(false);
        close2 = new QRadioButton(groupBox_4);
        close2->setObjectName(QStringLiteral("close2"));
        close2->setGeometry(QRect(50, 30, 82, 17));
        close3 = new QRadioButton(groupBox_4);
        close3->setObjectName(QStringLiteral("close3"));
        close3->setGeometry(QRect(90, 30, 82, 17));
        close4 = new QRadioButton(groupBox_4);
        close4->setObjectName(QStringLiteral("close4"));
        close4->setGeometry(QRect(130, 30, 82, 17));
        close5 = new QRadioButton(groupBox_4);
        close5->setObjectName(QStringLiteral("close5"));
        close5->setGeometry(QRect(10, 50, 82, 17));
        close6 = new QRadioButton(groupBox_4);
        close6->setObjectName(QStringLiteral("close6"));
        close6->setGeometry(QRect(50, 50, 82, 17));
        close7 = new QRadioButton(groupBox_4);
        close7->setObjectName(QStringLiteral("close7"));
        close7->setGeometry(QRect(90, 50, 82, 17));
        close8 = new QRadioButton(groupBox_4);
        close8->setObjectName(QStringLiteral("close8"));
        close8->setGeometry(QRect(130, 50, 82, 17));
        close9 = new QRadioButton(groupBox_4);
        close9->setObjectName(QStringLiteral("close9"));
        close9->setGeometry(QRect(10, 70, 31, 17));
        close1 = new QRadioButton(groupBox_4);
        close1->setObjectName(QStringLiteral("close1"));
        close1->setGeometry(QRect(10, 30, 41, 17));
        close10 = new QRadioButton(groupBox_4);
        close10->setObjectName(QStringLiteral("close10"));
        close10->setGeometry(QRect(50, 70, 82, 17));
        close11 = new QRadioButton(groupBox_4);
        close11->setObjectName(QStringLiteral("close11"));
        close11->setGeometry(QRect(90, 70, 82, 17));
        close12 = new QRadioButton(groupBox_4);
        close12->setObjectName(QStringLiteral("close12"));
        close12->setGeometry(QRect(130, 70, 82, 17));
        close2->raise();
        close3->raise();
        close4->raise();
        close5->raise();
        close6->raise();
        close7->raise();
        close8->raise();
        close1->raise();
        close10->raise();
        close11->raise();
        close12->raise();
        close9->raise();
        groupBox_3 = new QGroupBox(groupBox_8);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 20, 171, 101));
        open2 = new QRadioButton(groupBox_3);
        open2->setObjectName(QStringLiteral("open2"));
        open2->setGeometry(QRect(50, 30, 82, 17));
        open3 = new QRadioButton(groupBox_3);
        open3->setObjectName(QStringLiteral("open3"));
        open3->setGeometry(QRect(90, 30, 82, 17));
        open4 = new QRadioButton(groupBox_3);
        open4->setObjectName(QStringLiteral("open4"));
        open4->setGeometry(QRect(130, 30, 82, 17));
        open5 = new QRadioButton(groupBox_3);
        open5->setObjectName(QStringLiteral("open5"));
        open5->setGeometry(QRect(10, 50, 82, 17));
        open6 = new QRadioButton(groupBox_3);
        open6->setObjectName(QStringLiteral("open6"));
        open6->setGeometry(QRect(50, 50, 82, 17));
        open7 = new QRadioButton(groupBox_3);
        open7->setObjectName(QStringLiteral("open7"));
        open7->setGeometry(QRect(90, 50, 82, 17));
        open8 = new QRadioButton(groupBox_3);
        open8->setObjectName(QStringLiteral("open8"));
        open8->setGeometry(QRect(130, 50, 82, 17));
        open9 = new QRadioButton(groupBox_3);
        open9->setObjectName(QStringLiteral("open9"));
        open9->setGeometry(QRect(10, 70, 82, 17));
        open1 = new QRadioButton(groupBox_3);
        open1->setObjectName(QStringLiteral("open1"));
        open1->setGeometry(QRect(10, 30, 41, 17));
        open10 = new QRadioButton(groupBox_3);
        open10->setObjectName(QStringLiteral("open10"));
        open10->setGeometry(QRect(50, 70, 82, 17));
        open11 = new QRadioButton(groupBox_3);
        open11->setObjectName(QStringLiteral("open11"));
        open11->setGeometry(QRect(90, 70, 82, 17));
        open12 = new QRadioButton(groupBox_3);
        open12->setObjectName(QStringLiteral("open12"));
        open12->setGeometry(QRect(130, 70, 82, 17));
        groupBox_8->raise();
        groupBox->raise();
        groupBox_6 = new QGroupBox(ConfigProcess);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(10, 20, 181, 80));
        bot_cam1 = new QRadioButton(groupBox_6);
        bot_cam1->setObjectName(QStringLiteral("bot_cam1"));
        bot_cam1->setGeometry(QRect(10, 30, 161, 17));
        bot_cam1->setStyleSheet(QStringLiteral("color: rgb(0, 0, 255);"));
        bot_cam1->setCheckable(true);
        bot_cam1->setChecked(false);
        bot_cam2 = new QRadioButton(groupBox_6);
        bot_cam2->setObjectName(QStringLiteral("bot_cam2"));
        bot_cam2->setGeometry(QRect(10, 50, 151, 17));
        bot_cam2->setStyleSheet(QStringLiteral("color: rgb(0, 0, 255);"));
        groupBox_7 = new QGroupBox(ConfigProcess);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(770, 470, 571, 211));
        Slider_Rmin_2 = new QSlider(groupBox_7);
        Slider_Rmin_2->setObjectName(QStringLiteral("Slider_Rmin_2"));
        Slider_Rmin_2->setGeometry(QRect(60, 20, 400, 22));
        Slider_Rmin_2->setMaximum(255);
        Slider_Rmin_2->setOrientation(Qt::Horizontal);
        Slider_Gmin_2 = new QSlider(groupBox_7);
        Slider_Gmin_2->setObjectName(QStringLiteral("Slider_Gmin_2"));
        Slider_Gmin_2->setGeometry(QRect(60, 50, 400, 22));
        Slider_Gmin_2->setMaximum(255);
        Slider_Gmin_2->setOrientation(Qt::Horizontal);
        Slider_Bmin_2 = new QSlider(groupBox_7);
        Slider_Bmin_2->setObjectName(QStringLiteral("Slider_Bmin_2"));
        Slider_Bmin_2->setGeometry(QRect(60, 80, 400, 22));
        Slider_Bmin_2->setMaximum(255);
        Slider_Bmin_2->setOrientation(Qt::Horizontal);
        Slider_Rmax_2 = new QSlider(groupBox_7);
        Slider_Rmax_2->setObjectName(QStringLiteral("Slider_Rmax_2"));
        Slider_Rmax_2->setGeometry(QRect(60, 110, 400, 22));
        Slider_Rmax_2->setMaximum(255);
        Slider_Rmax_2->setOrientation(Qt::Horizontal);
        Slider_Gmax_2 = new QSlider(groupBox_7);
        Slider_Gmax_2->setObjectName(QStringLiteral("Slider_Gmax_2"));
        Slider_Gmax_2->setGeometry(QRect(60, 140, 400, 22));
        Slider_Gmax_2->setMaximum(255);
        Slider_Gmax_2->setOrientation(Qt::Horizontal);
        Slider_Bmax_2 = new QSlider(groupBox_7);
        Slider_Bmax_2->setObjectName(QStringLiteral("Slider_Bmax_2"));
        Slider_Bmax_2->setGeometry(QRect(60, 170, 400, 22));
        Slider_Bmax_2->setMaximum(255);
        Slider_Bmax_2->setOrientation(Qt::Horizontal);
        label_43 = new QLabel(groupBox_7);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(20, 20, 47, 13));
        label_44 = new QLabel(groupBox_7);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(20, 50, 47, 13));
        label_45 = new QLabel(groupBox_7);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(20, 80, 47, 13));
        label_46 = new QLabel(groupBox_7);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(20, 110, 47, 13));
        label_47 = new QLabel(groupBox_7);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(20, 140, 47, 13));
        label_48 = new QLabel(groupBox_7);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(20, 170, 47, 13));
        label_Rmin2 = new QLabel(groupBox_7);
        label_Rmin2->setObjectName(QStringLiteral("label_Rmin2"));
        label_Rmin2->setGeometry(QRect(490, 20, 47, 13));
        label_Rmin2->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_Rmin2->setAlignment(Qt::AlignCenter);
        label_Gmin2 = new QLabel(groupBox_7);
        label_Gmin2->setObjectName(QStringLiteral("label_Gmin2"));
        label_Gmin2->setGeometry(QRect(490, 50, 47, 13));
        label_Gmin2->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_Gmin2->setAlignment(Qt::AlignCenter);
        label_Bmin2 = new QLabel(groupBox_7);
        label_Bmin2->setObjectName(QStringLiteral("label_Bmin2"));
        label_Bmin2->setGeometry(QRect(490, 80, 47, 13));
        label_Bmin2->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_Bmin2->setAlignment(Qt::AlignCenter);
        label_Rmax2 = new QLabel(groupBox_7);
        label_Rmax2->setObjectName(QStringLiteral("label_Rmax2"));
        label_Rmax2->setGeometry(QRect(490, 110, 47, 13));
        label_Rmax2->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_Rmax2->setAlignment(Qt::AlignCenter);
        label_Gmax2 = new QLabel(groupBox_7);
        label_Gmax2->setObjectName(QStringLiteral("label_Gmax2"));
        label_Gmax2->setGeometry(QRect(490, 140, 47, 13));
        label_Gmax2->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_Gmax2->setAlignment(Qt::AlignCenter);
        label_Bmax2 = new QLabel(groupBox_7);
        label_Bmax2->setObjectName(QStringLiteral("label_Bmax2"));
        label_Bmax2->setGeometry(QRect(490, 170, 47, 13));
        label_Bmax2->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_Bmax2->setAlignment(Qt::AlignCenter);
        bot_Default = new QPushButton(ConfigProcess);
        bot_Default->setObjectName(QStringLiteral("bot_Default"));
        bot_Default->setGeometry(QRect(20, 600, 151, 21));
        groupBox_5->raise();
        buttonBox->raise();
        tabWidget->raise();
        tabWidget_2->raise();
        groupBox_2->raise();
        groupBox_6->raise();
        groupBox_7->raise();
        bot_Default->raise();

        retranslateUi(ConfigProcess);
        QObject::connect(Slider_Rmin_2, SIGNAL(valueChanged(int)), label_Rmin2, SLOT(setNum(int)));
        QObject::connect(Slider_Gmin_2, SIGNAL(valueChanged(int)), label_Gmin2, SLOT(setNum(int)));
        QObject::connect(Slider_Bmin_2, SIGNAL(valueChanged(int)), label_Bmin2, SLOT(setNum(int)));
        QObject::connect(Slider_Rmax_2, SIGNAL(valueChanged(int)), label_Rmax2, SLOT(setNum(int)));
        QObject::connect(Slider_Gmax_2, SIGNAL(valueChanged(int)), label_Gmax2, SLOT(setNum(int)));
        QObject::connect(Slider_Bmax_2, SIGNAL(valueChanged(int)), label_Bmax2, SLOT(setNum(int)));
        QObject::connect(Slider_Rmin, SIGNAL(valueChanged(int)), label_Rmin, SLOT(setNum(int)));
        QObject::connect(Slider_Gmin, SIGNAL(valueChanged(int)), label_Gmin, SLOT(setNum(int)));
        QObject::connect(Slider_Bmin, SIGNAL(valueChanged(int)), label_Bmin, SLOT(setNum(int)));
        QObject::connect(Slider_Rmax, SIGNAL(valueChanged(int)), label_Rmax, SLOT(setNum(int)));
        QObject::connect(Slider_Gmax, SIGNAL(valueChanged(int)), label_Gmax, SLOT(setNum(int)));
        QObject::connect(Slider_Bmax, SIGNAL(valueChanged(int)), label_Bmax, SLOT(setNum(int)));
        QObject::connect(buttonBox, SIGNAL(rejected()), ConfigProcess, SLOT(reject()));
        QObject::connect(buttonBox, SIGNAL(accepted()), ConfigProcess, SLOT(accept()));

        tabWidget->setCurrentIndex(0);
        tabWidget_2->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(ConfigProcess);
    } // setupUi

    void retranslateUi(QDialog *ConfigProcess)
    {
        ConfigProcess->setWindowTitle(QApplication::translate("ConfigProcess", "Configura\303\247\303\265es de processamento", 0));
        label_Original->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_Original), QApplication::translate("ConfigProcess", "Original", 0));
        label_Fundo->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_Fundo), QApplication::translate("ConfigProcess", "Fundo", 0));
        label_Subt->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_Subt), QApplication::translate("ConfigProcess", "Subtra\303\247\303\243o", 0));
        label_Proc->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_Proc), QApplication::translate("ConfigProcess", "Processada", 0));
        label_Limiar1->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("ConfigProcess", "Limiar1", 0));
        label_Limiar2->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("ConfigProcess", "Limiar2", 0));
        label_Soma->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("ConfigProcess", "Soma", 0));
        label_Open->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("ConfigProcess", "Abertura", 0));
        label_Close->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("ConfigProcess", "Fechamento", 0));
        label_Original_2->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_Original_2), QApplication::translate("ConfigProcess", "Original", 0));
        label_Fundo_2->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_Fundo_2), QApplication::translate("ConfigProcess", "Fundo", 0));
        label_Subt_2->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_Subt_2), QApplication::translate("ConfigProcess", "Subtra\303\247\303\243o", 0));
        label_Proc_2->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_Proc_2), QApplication::translate("ConfigProcess", "Processada", 0));
        label_Limiar1_2->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_6), QApplication::translate("ConfigProcess", "Limiar1", 0));
        label_Limiar2_2->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_7), QApplication::translate("ConfigProcess", "Limiar2", 0));
        label_Soma_2->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_8), QApplication::translate("ConfigProcess", "Soma", 0));
        label_Open_2->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_9), QApplication::translate("ConfigProcess", "Abertura", 0));
        label_Close_2->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_10), QApplication::translate("ConfigProcess", "Fechamento", 0));
        groupBox_2->setTitle(QApplication::translate("ConfigProcess", "LIMIAR RGB 1", 0));
        label_19->setText(QApplication::translate("ConfigProcess", "Rmin", 0));
        label_20->setText(QApplication::translate("ConfigProcess", "Gmin", 0));
        label_21->setText(QApplication::translate("ConfigProcess", "Bmin", 0));
        label_22->setText(QApplication::translate("ConfigProcess", "Rmax", 0));
        label_23->setText(QApplication::translate("ConfigProcess", "Gmax", 0));
        label_24->setText(QApplication::translate("ConfigProcess", "Bmax", 0));
        label_Rmin->setText(QString());
        label_Gmin->setText(QString());
        label_Bmin->setText(QString());
        label_Rmax->setText(QString());
        label_Gmax->setText(QString());
        label_Bmax->setText(QString());
        groupBox_5->setTitle(QApplication::translate("ConfigProcess", "ABERTURA LINEAR", 0));
        groupBox->setTitle(QApplication::translate("ConfigProcess", "Filtro passa-baixa", 0));
        filter3->setText(QApplication::translate("ConfigProcess", "3", 0));
        filter5->setText(QApplication::translate("ConfigProcess", "5", 0));
        filter7->setText(QApplication::translate("ConfigProcess", "7", 0));
        filter9->setText(QApplication::translate("ConfigProcess", "9", 0));
        filter11->setText(QApplication::translate("ConfigProcess", "11", 0));
        filter13->setText(QApplication::translate("ConfigProcess", "13", 0));
        filter15->setText(QApplication::translate("ConfigProcess", "15", 0));
        filter17->setText(QApplication::translate("ConfigProcess", "17", 0));
        filter1->setText(QApplication::translate("ConfigProcess", "1", 0));
        filter19->setText(QApplication::translate("ConfigProcess", "19", 0));
        filter21->setText(QApplication::translate("ConfigProcess", "21", 0));
        filter23->setText(QApplication::translate("ConfigProcess", "23", 0));
        groupBox_8->setTitle(QApplication::translate("ConfigProcess", "ITERA\303\207\303\225ES", 0));
        groupBox_4->setTitle(QApplication::translate("ConfigProcess", "Morfologia Fechamento", 0));
        close2->setText(QApplication::translate("ConfigProcess", "2", 0));
        close3->setText(QApplication::translate("ConfigProcess", "3", 0));
        close4->setText(QApplication::translate("ConfigProcess", "4", 0));
        close5->setText(QApplication::translate("ConfigProcess", "5", 0));
        close6->setText(QApplication::translate("ConfigProcess", "6", 0));
        close7->setText(QApplication::translate("ConfigProcess", "7", 0));
        close8->setText(QApplication::translate("ConfigProcess", "8", 0));
        close9->setText(QApplication::translate("ConfigProcess", "9", 0));
        close1->setText(QApplication::translate("ConfigProcess", "1", 0));
        close10->setText(QApplication::translate("ConfigProcess", "10", 0));
        close11->setText(QApplication::translate("ConfigProcess", "11", 0));
        close12->setText(QApplication::translate("ConfigProcess", "12", 0));
        groupBox_3->setTitle(QApplication::translate("ConfigProcess", "Morfologia Abertura", 0));
        open2->setText(QApplication::translate("ConfigProcess", "2", 0));
        open3->setText(QApplication::translate("ConfigProcess", "3", 0));
        open4->setText(QApplication::translate("ConfigProcess", "4", 0));
        open5->setText(QApplication::translate("ConfigProcess", "5", 0));
        open6->setText(QApplication::translate("ConfigProcess", "6", 0));
        open7->setText(QApplication::translate("ConfigProcess", "7", 0));
        open8->setText(QApplication::translate("ConfigProcess", "8", 0));
        open9->setText(QApplication::translate("ConfigProcess", "9", 0));
        open1->setText(QApplication::translate("ConfigProcess", "1", 0));
        open10->setText(QApplication::translate("ConfigProcess", "10", 0));
        open11->setText(QApplication::translate("ConfigProcess", "11", 0));
        open12->setText(QApplication::translate("ConfigProcess", "12", 0));
        groupBox_6->setTitle(QApplication::translate("ConfigProcess", "SELECIONAR ENTRADA", 0));
        bot_cam1->setText(QApplication::translate("ConfigProcess", "Captura 1 - C\303\242mera / Video", 0));
        bot_cam2->setText(QApplication::translate("ConfigProcess", "Captura 2 - C\303\242mera / Video", 0));
        groupBox_7->setTitle(QApplication::translate("ConfigProcess", "LIMIAR RGB 2", 0));
        label_43->setText(QApplication::translate("ConfigProcess", "Rmin", 0));
        label_44->setText(QApplication::translate("ConfigProcess", "Gmin", 0));
        label_45->setText(QApplication::translate("ConfigProcess", "Bmin", 0));
        label_46->setText(QApplication::translate("ConfigProcess", "Rmax", 0));
        label_47->setText(QApplication::translate("ConfigProcess", "Gmax", 0));
        label_48->setText(QApplication::translate("ConfigProcess", "Bmax", 0));
        label_Rmin2->setText(QString());
        label_Gmin2->setText(QString());
        label_Bmin2->setText(QString());
        label_Rmax2->setText(QString());
        label_Gmax2->setText(QString());
        label_Bmax2->setText(QString());
        bot_Default->setText(QApplication::translate("ConfigProcess", "Carregar padr\303\243o", 0));
    } // retranslateUi

};

namespace Ui {
    class ConfigProcess: public Ui_ConfigProcess {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CONFIGPROCESS_H
